import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1920,height:1080} });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('https://kimhyunwoo-flyworker.static.hf.space/', {waitUntil:'load', timeout:90000});
await p.waitForFunction(()=>document.querySelector('#emps .emp .st')?.textContent?.includes('On shift'),{timeout:180000});
await p.click('#toByo'); await p.click('#byoSample');
await p.waitForFunction(()=>/Attached/.test(document.querySelector('#byoNote').textContent),{timeout:40000});
console.log('라이브 붙음:', (await p.textContent('#byoNote')).trim().slice(0,90));
await p.waitForTimeout(18000);
const bugs = await p.$$eval('.bug .lb', ns=>[...new Set(ns.map(n=>n.textContent))]);
console.log('발견:', bugs.join(' | ')||'아직 없음');
await p.evaluate(()=>document.querySelector('#toByo').closest('.panel').scrollIntoView({block:'start'}));
await p.waitForTimeout(600);
await p.screenshot({path:'submit/shots/6-byo.png'});
console.log('오류:', errs.length?errs:'없음');
await b.close();
