import { chromium } from 'playwright';
const b=await chromium.launch({headless:false,args:['--enable-unsafe-webgpu']});
const p=await b.newPage({viewport:{width:1600,height:1000}});
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{if(m.type()==='error')errs.push('C:'+m.text().slice(0,90));});
await p.goto('https://kimhyunwoo-flyworker.static.hf.space/',{waitUntil:'load',timeout:120000});
await p.waitForTimeout(4000);
await p.screenshot({path:'/tmp/L1.png'});
await p.waitForFunction(()=>document.querySelector('#emps .emp .st')?.textContent?.includes('On shift'),null,{timeout:180000});
console.log('근무 시작 확인');
console.log('표:', (await p.$$eval('#compare tr',rs=>rs.map(r=>[...r.children].map(c=>c.textContent.trim()).join(' ')))).slice(0,2).join(' // '));
await p.evaluate(()=>document.querySelector('.workbench').scrollIntoView({block:'start'}));
await p.waitForTimeout(1000); await p.screenshot({path:'/tmp/L2.png'});
const m=await b.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3});
await m.goto('https://kimhyunwoo-flyworker.static.hf.space/',{waitUntil:'load',timeout:120000});
await m.waitForTimeout(3000);
console.log('모바일 가로스크롤:', await m.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1));
await m.screenshot({path:'/tmp/L3.png'});
console.log('오류:', errs.length?errs.slice(0,3):'없음');
await b.close();
